Jenkinsfile, build.gradle
Bugfix backport. 
Auto-propagering av byggen borttagen från pipeline.
=> INTYGFV-10875: Bugfix backport för att kunna hotfixa rehabstöd

ts/ts-diabetes/src/main/resources/META-INF/resources/webjars/ts-diabetes/webcert/views/patientHelper.v2.service.js, ts/ts-diabetes/src/main/resources/META-INF/resources/webjars/ts-diabetes/webcert/views/patientHelper.v3.service.js
Ändrade även kommentarerna till rätt patientstatus kod.
=> INTYGFV-11054: visa ps-03 för ts-diabetes v3

pdf/src/main/java/se/inera/intyg/common/pdf/eventhandler/IntygHeader.java
=> INTYGFV-11011: /

pdf/src/main/java/se/inera/intyg/common/pdf/model/UVList.java
=> INTYGFV-11041: Fixat bugg i UvList-komponenten för Ej angivet

build.gradle, util/integration-util/src/main/java/se/inera/intyg/common/util/integration/interceptor/SoapFaultToSoapResponseTransformerInterceptor.java
=> Revert "INTYGFV-11093: Updated CXF version to 3.1.15"

build.gradle
Använd senaste schema version rivtaClinicalprocessSchemasVersion 4.0.2
=> INTYGFV-10829: Bumped rivtaClinicalprocessSchemasVersion

fk/lisjp/src/main/resources/META-INF/resources/webjars/lisjp/webcert/views/lisjpSupportPanelConfig.factory.js
SRS skall ej synas vid låst utkast
Finns en PR för release också.
=> NEW-SRS: Fixat så att SRS inte syns för låsta utkast (ppid-984)

web/src/main/resources/META-INF/resources/webjars/common/webcert/components/wcSupportPanelManager/wcSrsPanelTab/common/srs.proxy.js, web/src/main/resources/META-INF/resources/webjars/common/webcert/components/wcSupportPanelManager/wcSrsPanelTab/wcSrsPanelTab.directive.html, web/src/main/resources/META-INF/resources/webjars/common/webcert/components/wcSupportPanelManager/wcSrsPanelTab/wcSrsPanelTab.directive.js, web/src/main/resources/META-INF/resources/webjars/common/webcert/components/wcSupportPanelManager/wcSrsPanelTab/wcSrsRecommendationList.directive.js, web/src/main/resources/META-INF/resources/webjars/common/webcert/components/wcSupportPanelManager/wcSrsPanelTab/wcSrsResult.directive.html
Samma PR som i release-branchen
* Samtycke skall vara disabled vid förlängning
* Översyn av felmeddelanden
* Uppdatering av texter
=> NEW-SRS: (pp-id 999, 986, 991)

pdf/src/test/resources/tsbas/tsbas-up.js, ts/ts-bas/src/main/java/se/inera/intyg/common/ts_bas/v6/codes/TsBasKorkortsbehorighetKod.java, ts/ts-bas/src/main/java/se/inera/intyg/common/ts_bas/v6/model/converter/TransportToInternal.java, ts/ts-bas/src/main/java/se/inera/intyg/common/ts_bas/v6/model/converter/UtlatandeToIntyg.java, ts/ts-bas/src/main/java/se/inera/intyg/common/ts_bas/v6/model/internal/Bedomning.java, ts/ts-bas/src/main/java/se/inera/intyg/common/ts_bas/v6/model/internal/BedomningKorkortstyp.java, ts/ts-bas/src/main/java/se/inera/intyg/common/ts_bas/v6/validator/internal/InternalValidatorInstance.java, ts/ts-bas/src/main/resources/META-INF/resources/webjars/ts-bas/app-shared/tsbasViewConfig.v6.factory.js, ts/ts-bas/src/main/resources/META-INF/resources/webjars/ts-bas/webcert/views/utkast/utkast.v6.model.js, ts/ts-bas/src/main/resources/ts-bas-uv-viewmodel.v6.js, ts/ts-bas/src/test/java/se/inera/intyg/common/ts_bas/v6/rest/TsBasModuleApiTest.java, ts/ts-bas/src/test/resources/v6/scenarios/internal/ts-bas-bedomning-c-changed-format.json, ts/ts-bas/src/test/resources/v6/scenarios/internal/ts-bas-bedomning-c-old-format.json, ts/ts-bas/src/test/resources/v6/scenarios/internal/ts-bas-bedomning-kan-inte-ta-stallning-changed-format.json, ts/ts-bas/src/test/resources/v6/scenarios/internal/ts-bas-bedomning-kan-inte-ta-stallning-old-format.json
Rättningen är införd i develop i fredags men missades att mergas till 2019.3 releasebranchen.
=> INTYGFV-11096: Pull request till 2019.3.

web/src/main/resources/META-INF/resources/webjars/common/minaintyg/components/latestEvents/miRelevantEvent.filter.js, web/src/main/resources/META-INF/resources/webjars/common/minaintyg/components/latestEvents/miRelevantEvent.filter.spec.js, web/src/main/resources/META-INF/resources/webjars/common/minaintyg/messages.js
Två commits en i common och en i MI
=> INTYGFV-11446: Lagt till status Kompletterar på intyg

web/src/main/resources/META-INF/resources/webjars/common/webcert/utkast/utkastHeader/wcUtkastHeader/wcUtkastHeader.directive.html, web/src/main/resources/META-INF/resources/webjars/common/webcert/utkast/wcUtkastDeleted/wcUtkastDeletedModal/wcUtkastDeletedModal.directive.js
Det är endast wc-utkast-deleted-modal som jag lagt till i wcUtkastHeader, resterande är indentering som ändrats.
=> INTYGFV-11293: Removed delay and added modal for copied drafts

ts/ts-diabetes/src/main/java/se/inera/intyg/common/ts_diabetes/v3/validator/InternalDraftValidatorImpl.java
INTYGFV-13481: Fixed category on validation error
=> INTYGFV-12985: Allow printing within the same care provider.

skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/rest/Ag7804ModuleApiV1.java, skl/ag7804/src/main/resources/META-INF/resources/webjars/ag7804/webcert/views/messages.js, sos/doi/src/main/java/se/inera/intyg/common/doi/v1/rest/DoiModuleApiV1.java, support/src/main/java/se/inera/intyg/common/support/modules/support/api/GetCopyFromCriteria.java
and GetCopyFromCriteria all together
=> INTYGFV-13176: Remove age restriction on FK7804 candidate

build.gradle
Fixed validation rules R4, R8, R9, R10 for TS-diabetes V3
=> INTYGFV-13611: New Schematron version

services/src/main/java/se/inera/intyg/common/services/texts/IntygTextsService.java, services/src/main/java/se/inera/intyg/common/services/texts/IntygTextsServiceImpl.java, services/src/test/java/se/inera/intyg/common/services/texts/IntygTextsServiceImplTest.java
I need this method to solve INTYGFV-13983,
=> INTYGFV-13517: Added method to check latest major version.

fk/lisjp/src/main/java/se/inera/intyg/common/lisjp/v1/model/converter/InternalToCertificate.java, fk/lisjp/src/test/java/se/inera/intyg/common/lisjp/v1/model/converter/InternalToCertificateTest.java, skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/model/converter/InternalToCertificate.java, skl/ag7804/src/test/java/se/inera/intyg/common/ag7804/v1/model/converter/InternalToCertificateTest.java, support/src/main/java/se/inera/intyg/common/support/facade/model/CertificateDataElementStyleEnum.java, support/src/main/java/se/inera/intyg/common/support/facade/model/config/CertificateDataConfig.java, support/src/main/java/se/inera/intyg/common/support/facade/model/config/CertificateDataConfigRadioMultipleCodeOptionalDropdown.java, support/src/main/java/se/inera/intyg/common/support/facade/model/config/RadioMultipleCodeOptionalDropdown.java
This enables hiding of questions, which is currently needed to render a question in another place than the flat structure and not have it duplicated.
=> INTYGFV-14131: Created new config type, CertificateDataConfigRadioMultipleCodeOptionalDropdown and added HIDDEN style

web/src/main/resources/META-INF/resources/webjars/common/webcert/utkast/utkastHeader/wcUtkastHeader/wcUtkastHeader.directive.js
Updated text to new specification.
=> INTYGFV-14011: Updated text.

web/src/main/resources/META-INF/resources/webjars/common/webcert/utkast/utkastHeader/wcUtkastHeader/wcUtkastHeader.directive.js
Updated to show middle name and format personnr.
=> INTYGFV-14011: Updated to show middle name.

web/src/main/resources/META-INF/resources/webjars/common/webcert/utkast/utkastHeader/wcUtkastHeader/wcUtkastHeader.directive.js
You should only get a popup if you can sign a DB-draft.
=> INTYGFV-14011: Added check to only display modal if you can sign it.

support/src/main/java/se/inera/intyg/common/support/facade/model/user/LoginMethod.java
https://github.com/sklintyg/frontend/pull/484
https://github.com/sklintyg/webcert/pull/767
=> INTYGFV-14467: Distinguish between mobile and desktop bank_id login

support/src/main/java/se/inera/intyg/common/support/facade/util/ValueToolkit.java, support/src/main/java/se/inera/intyg/common/support/validate/ValidatorUtil.java, support/src/test/java/se/inera/intyg/common/support/facade/util/ValueToolkitTest.java
Fixed redundant code that broke spotbugs. Added tests.
=> INTYGFV-14815: Fixed redundant code that broke spotbugs. Added tests.

sos/doi/src/main/java/se/inera/intyg/common/doi/v1/model/converter/InternalToCertificate.java, sos/doi/src/main/java/se/inera/intyg/common/doi/v1/model/converter/certificate/question/QuestionBidragandeSjukdomar.java, sos/doi/src/main/java/se/inera/intyg/common/doi/v1/model/converter/certificate/question/QuestionTerminalDodsorsakFoljdAv.java, sos/doi/src/main/java/se/inera/intyg/common/doi/v1/validator/InternalDraftValidatorImpl.java, sos/doi/src/test/java/se/inera/intyg/common/doi/v1/model/converter/CertificateToInternalTest.java, sos/doi/src/test/java/se/inera/intyg/common/doi/v1/model/converter/certificate/question/QuestionBidragandeSjukdomarTest.java, sos/doi/src/test/java/se/inera/intyg/common/doi/v1/model/converter/certificate/question/QuestionTerminalDodsorsakFoljdAvTest.java, sos/doi/src/test/java/se/inera/intyg/common/doi/v1/validator/InternalDraftValidatorImplTest.java
Also refactored QuestionTerminalDodsorsakFoljdAv & QuestionBidragandeSjukdom to use ids that can be used to identifiy certain components from frontend.
=> INTYGFV-14992: Added questionId to InternalDraftValidatorImpl for DOI.

fk/fk-parent/src/main/java/se/inera/intyg/common/fkparent/model/converter/RespConstants.java, fk/fk-parent/src/main/java/se/inera/intyg/common/fkparent/model/converter/certificate/AbstractQuestionDiagnoser.java, fk/lisjp/src/test/java/se/inera/intyg/common/lisjp/v1/model/converter/certificate/question/QuestionDiagnoserTest.java, fk/luae_fs/src/test/java/se/inera/intyg/common/luae_fs/v1/model/converter/certificate/question/QuestionDiagnoserTest.java, fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionDiagnosForNyBedomning.java, fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionDiagnosgrund.java, fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionNyBedomningDiagnosgrund.java, fk/luae_na/src/main/java/se/inera/intyg/common/luae_na/v1/validator/InternalDraftValidatorImpl.java, fk/luae_na/src/test/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionDiagnoserTest.java, fk/luae_na/src/test/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionDiagnosgrundTest.java, fk/luae_na/src/test/java/se/inera/intyg/common/luae_na/v1/model/converter/certificate/question/QuestionNyBedomningDiagnosgrundTest.java, fk/luae_na/src/test/java/se/inera/intyg/common/luae_na/v1/validator/InternalDraftValidatorTest.java
Also fixed some wrongly used questionIds.
=> INTYGFV-15113: Refactored ids for AbstractQuestionDiagnoser to match field in validationErrors.

services/src/main/java/se/inera/intyg/common/services/texts/DefaultCertificateTextProvider.java
Same replace is found on line 74 in the same method.
=> INTYGFV-14490: Removed redundand duplicate code in DefaultCertificateTextProvider.

web/src/main/resources/META-INF/resources/webjars/common/webcert/user/user.model.js
=> INTYGFV-16277: Handle role sjukskoterska in angular client.

fk/fk-parent/src/main/java/se/inera/intyg/common/fkparent/model/validator/ValidatorUtilFK.java, fk/fk-parent/src/test/java/se/inera/intyg/common/fkparent/model/validator/ValidatorUtilFKTest.java, skl/ag7804/src/main/java/se/inera/intyg/common/ag7804/v1/validator/ValidatorUtil.java
=> INTYGFV-16503: Update so that correct field is highlighted for diagnosis error messages.
